serverless-cdk-plugin: Add ServerlessConstruct typing
swarmion/swarmion pull request #207
Opened 2022-07-19 00:14 UTC by GuillaumeLagrange

This PR updates root tsconfig's node resolution to node16 by default.
We do this to support the exports feature, as per this issue: 
https://github.com/microsoft/TypeScript/issues/33079#issuecomment-1169377037

The alternative we have would be to set the typeVersions as suggested here:
https://github.com/microsoft/TypeScript/issues/33079#issuecomment-1169419172

I am open to whichever solution you guys favor. I am convinced we need the double export because we do not want to maintain two packages going forward with this plugin.

A follow up which would be nice would be to update the eslint rule to allow non-root internal imports if the import targets an entry point of the imported package. I will create the issue if this PR gets approved

2022-07-19 09:00 UTC, adriencaccia requested changes
Great work :rocket:

Your plan for the `eslint` import rule is fine with me

2022-07-19 15:47 UTC, fargito commented on tsconfig.json
> +    "moduleResolution": "node16",
Why is this needed?

2022-07-22 12:17 UTC, GuillaumeLagrange commented on backend/orchestrator/serverless.ts
> +  serverlessConstruct: OrchestratorDynamodb,
C O N S T R U C T

2022-07-22 14:41 UTC, GuillaumeLagrange commented
We are closing this MR because we found a more pragmatic solution by exporting anything we need in the plugin class. We are opening a new MR and adressing all the comments unrelated to the import strategy over there (#213 )

This MR stays as his, but closed, in order to keep a diff in case we want to dig into the exports keyword in a near future

2022-07-22 14:41 UTC, closed without merging

2022-07-22 14:47 UTC, Eikix commented on packages/serverless-cdk-plugin/README.md
> +  serverlessConstruct: MyConstruct,
For now yes

2022-07-22 14:48 UTC, Eikix commented on backend/orchestrator/package.json
> +    "@swarmion/serverless-cdk-plugin": "0.8.8",
ok

2022-07-22 15:04 UTC, Eikix commented on packages/serverless-cdk-plugin/README.md
> +Typically you would create a construct in the desired folder. For instance, a DynamoDB construct.
Ok

2022-07-22 15:08 UTC, Eikix commented on packages/serverless-cdk-plugin/package.json
> +  "types": "./dist/types/index.d.ts",
Ok

2022-07-22 15:08 UTC, Eikix commented on backend/orchestrator/serverless.ts
> +    // ...cdkResources,
Ok

2022-07-22 15:08 UTC, Eikix commented on packages/serverless-cdk-plugin/README.md
> +- The plugin does not yet allow for referencing lambda resources coming from Serverless framework inside CDK construct code. This feature will be available in a second release.
Actually this feature is available now.

2022-07-22 15:09 UTC, Eikix commented on packages/serverless-cdk-plugin/README.md
> +<img width="500" height="500" src="./static/lambda-sqs-lambda.drawio.svg"/>
Sure, how about lambda-and-sqs-integration