Serverless construct static export
swarmion/swarmion pull request #213
Opened 2022-07-22 14:21 UTC by Eikix

A new version of the serverless cdk plugin that does not utilize the "exports" syntax of the package.json file.

2022-07-22 15:11 UTC, GuillaumeLagrange requested changes

2022-07-22 15:11 UTC, GuillaumeLagrange commented on backend/orchestrator/package.json
> +    "@swarmion/serverless-cdk-plugin": "0.8.8",
carret here to stay consistent

2022-07-22 15:11 UTC, GuillaumeLagrange commented on backend/orchestrator/resources/dynamodb.ts
> +import type { ServerlessProps } from '@swarmion/serverless-cdk-plugin';
Does this work ?
```typescript
import { ServerlessProps, getCdkPropertyHelper, ServerlessConstruct } from '@swarmion/serverless-cdk-plugin';
```

2022-07-22 15:11 UTC, GuillaumeLagrange commented on backend/orchestrator/resources/dynamodb.ts
> +import type { ServerlessProps } from '@swarmion/serverless-cdk-plugin';
If it doesn't we should go with

```typescript
import ServerlessCdkPlugin, { ServerlessProps } from '@swarmion/serverless-cdk-plugin';
```

2022-07-22 15:11 UTC, GuillaumeLagrange commented on backend/orchestrator/serverless.ts
> +  serverlessConstruct: OrchestratorDynamodb,
rename this key `construct` in `CdkPluginConfig`

2022-07-22 15:11 UTC, GuillaumeLagrange commented on packages/serverless-cdk-plugin/README.md
> +Typically you would create a construct in the desired folder. For instance, a DynamoDB construct.
from the old PR by @adriencaccia 

We shouldn't use 'you' and keep everything third person

+ remove typically .... would formulation to be more assertive

2022-07-22 15:11 UTC, GuillaumeLagrange commented on packages/serverless-cdk-plugin/README.md
> +Then, you would pass the construct to the `serverless.ts` file at the serverlessConstruct key:
third person

2022-07-22 15:11 UTC, GuillaumeLagrange commented on packages/serverless-cdk-plugin/README.md
> +And that's it! You can now reference your DynamoDB in your Serverless framework code seamlessly (e.g. in your lambdas).
and also here third person :)

2022-07-22 15:11 UTC, GuillaumeLagrange commented on packages/serverless-cdk-plugin/README.md
>  }
squash this commit with the previous commit

2022-07-22 15:11 UTC, GuillaumeLagrange commented on backend/orchestrator/package.json
> +    "@swarmion/serverless-cdk-plugin": "0.8.8",
carret here

2022-07-22 15:11 UTC, GuillaumeLagrange commented on packages/serverless-cdk-plugin/src/types/cdkPluginConfig.ts
>  export type CdkPluginConfig = {
open question: shouldn't we rename this to `ServerlessCdkPluginConfig` to be more in line with the plugin name ? Not sure what's the convention here @CorentinDoue

2022-07-22 15:11 UTC, GuillaumeLagrange commented on packages/serverless-cdk-plugin/static/lambda-sqs-lambda.drawio.svg
> +<?xml version="1.0" encoding="UTF-8"?>
Make the name clearer (comment from the old PR)

2022-07-22 15:11 UTC, GuillaumeLagrange commented on packages/serverless-cdk-plugin/src/types/cdkPluginConfig.ts
> +  serverlessConstruct: typeof ServerlessConstruct;
we want to keep this as a Construct imo. And dynamically check if it's a serverless Construct to give the props

2022-07-22 15:11 UTC, GuillaumeLagrange commented on packages/serverless-cdk-plugin/src/serverlessCdk.ts
> +      serverless: serverlessConfigFile,
dynamically check if we have a `ServerlessConstruct` and only give the props if we have. We want to stay compatible with simple `Construct`

2022-07-22 15:15 UTC, CorentinDoue commented on packages/serverless-cdk-plugin/integrationTests/defaultUsage/serverless.ts
> +        ),
c'est quoi ça ?

2022-07-22 15:28 UTC, Eikix commented on packages/serverless-cdk-plugin/integrationTests/defaultUsage/serverless.ts
> +        ),
C'est pour tester si le construct cdk a accès à des valeurs internes au sls config file

2022-07-22 16:28 UTC, GuillaumeLagrange approved these changes
🚀🚀🚀🚀

2022-07-22 16:29 UTC, GuillaumeLagrange commented
@adriencaccia or @fargito this time we're ready 👀

Sorry for all the different PRs on this subject

2022-07-25 09:23 UTC, fargito approved these changes
Great work!

2022-07-25 09:24 UTC, merged