Feat/add event contracts
swarmion/swarmion pull request #231
Opened 2022-08-05 15:22 UTC by StanHannebelle

This is to add event contracts enabling to define EventContract instances.
The first available feature is _getEventBridgeLambdaTrigger()_

It can be used as follows in the config of a lambda:

```
{
events: [
    getEventBridgeTrigger(
      eventBridgeEventContract,
      {
        'Fn::GetAtt': ['EventBridge', 'Name'],  // to find the correct eventbus name
      },
    ),
  ],
...
}
```

Then, the lambda will be triggered when an event with the following pattern is published on the specified bus:

```
{
  "detail-type": [
    eventBridgeEventContract.name
  ],
  "source": [
   eventBridgeEventContract.source
  ]
}
```

2022-08-26 12:45 UTC, adriencaccia commented
@StanHannebelle as seen together, can you add some documentation on this new contract? 🙏

2022-08-26 15:43 UTC, StanHannebelle commented
@adriencaccia just updated the PR with the corresponding doc!

2022-08-26 15:52 UTC, adriencaccia requested changes

2022-08-26 15:52 UTC, adriencaccia commented on user-docs/documentation/docs/how-to-guides/1-use-serverless-contracts/3-event.md
> +```
To match the doc format that @Sc0ra introduced, we can add a section:

```
### Type the lambda input and output

Coming soon!
```

2022-09-08 12:28 UTC, fargito commented on packages/serverless-contracts/src/contracts/event/types/lambdaTrigger.ts
> +type LambdaEvents = Unpacked<LambdaFunction['events']>;
Did you copy/paste this? Shouldn't this be moved elsewhere?

2022-10-07 13:43 UTC, fargito commented
Still needed:
- update the docs
- implement isomorphism on `getHandler`
- add `getPublishEvent` function to publish to the bus

2022-10-24 19:36 UTC, fargito commented on packages/serverless-contracts/src/contracts/eventBridge/features/lambdaTrigger.ts
> +    source: [contract.source],
Sources instead of single source

2022-10-24 19:36 UTC, fargito commented on packages/serverless-contracts/src/contracts/apiGateway/index.ts
> -  getTrigger,
Add it back with its new name + fix imports

2022-10-24 19:36 UTC, fargito commented on packages/serverless-contracts/src/contracts/eventBridge/index.ts
> +export { getEventBridgeHandler } from './features';
Also add the trigger

2022-10-24 19:37 UTC, fargito commented on packages/serverless-contracts/src/features/lambdaHandler.ts
> +import { PayloadType } from 'contracts/eventBridge/types/common';
Rename + export from `'contracts/eventBridge/types'`

2022-10-24 19:38 UTC, fargito commented on packages/serverless-contracts/src/features/lambdaHandler.ts
> +  HandlerType as EventBridgeInnerHandlerType,
Rename

2022-10-24 19:38 UTC, fargito commented on packages/serverless-contracts/src/features/lambdaHandler.ts
> +  HandlerType as ApiGatewayInnerHandlerType,
Rename

2022-10-24 19:38 UTC, fargito commented on packages/serverless-contracts/src/features/lambdaTrigger.ts
> +export const getTrigger = <Contract extends ServerlessContract>(
Maybe use overloading instead of heavy type computation

2022-10-24 20:04 UTC, fargito commented on packages/serverless-contracts/src/contracts/eventBridge/__tests__/lambdaHandler.test.ts
> +    source: 'toto.tata',
source

2022-10-24 20:59 UTC, fargito commented on packages/serverless-contracts/src/contracts/eventBridge/__tests__/lambdaTrigger.test.ts
> +      source: 'toto.tata',
source

2022-10-25 21:22 UTC, closed without merging