fix(serverless-contracts): fix handler type to allow middy usage
swarmion/swarmion pull request #334
Opened 2022-11-01 13:44 UTC by Sc0ra

Fix #308

2022-11-03 08:48 UTC, fargito requested changes

2022-11-03 08:48 UTC, fargito commented on packages/serverless-contracts/src/contracts/apiGateway/features/lambdaHandler.ts
> +  async (event, context, callback, ...additionalArgs) => {
As discussed together, could you add the same interface for the `EventBridgeContract`?

2022-11-04 14:09 UTC, fargito commented on packages/serverless-contracts/package.json
> +    "@middy/http-cors": "^3.6.2",
Isn't there a mismatch here?

2022-11-04 14:09 UTC, fargito commented on packages/serverless-contracts/package.json
> +    "middy": "^0.36.0",
Is this the correct dependency?

2022-11-04 14:31 UTC, fargito commented on packages/serverless-contracts/src/contracts/apiGateway/features/lambdaHandler.ts
>      // because we have asynchronous handlers
This should be deleted then

2022-11-04 14:33 UTC, fargito commented on packages/serverless-contracts/src/contracts/eventBridge/features/lambdaHandler.ts
>      // because we have asynchronous handlers
Should also be deleted

2022-11-04 14:33 UTC, fargito commented on packages/serverless-contracts/src/contracts/apiGateway/types/lambdaHandler.ts
> +  callback?: Callback,
```suggestion
  callback: Callback,
```
?

2022-11-04 15:00 UTC, Sc0ra commented on packages/serverless-contracts/src/contracts/apiGateway/types/lambdaHandler.ts
> +  callback?: Callback,
ça je sais pas justement, ça nous permettrait de pas être obligé de le définir si il n'y a pas d'additional args, et middy est content

2022-11-04 16:25 UTC, fargito approved these changes

2022-11-04 16:32 UTC, merged