Feat/output schemas no retro
swarmion/swarmion pull request #404
Opened 2022-12-16 13:56 UTC by Sc0ra

2022-12-16 14:17 UTC, fargito commented on packages/serverless-contracts/src/contracts/apiGateway/features/fetchRequest.ts
> +  } as OutputType<Contract>;
😍

2022-12-16 14:18 UTC, fargito commented on packages/serverless-contracts/src/contracts/apiGateway/features/lambdaHandler.ts
> +/* eslint-disable complexity */
Why is this necessary?

2022-12-16 14:19 UTC, fargito commented on packages/serverless-contracts/src/contracts/apiGateway/features/lambdaHandler.ts
> +    } = Exclude<O.UnionOf<Outputs>, undefined>,
Maybe this is too complex, now that we are accepting the breaking change

2022-12-16 14:51 UTC, Sc0ra commented on packages/serverless-contracts/src/contracts/apiGateway/features/lambdaHandler.ts
> +/* eslint-disable complexity */
It was not, i removed it

2022-12-16 17:28 UTC, fargito approved these changes
Excellent work, thanks @Sc0ra and @StanHannebelle!

However I would prefer we create an alpha release in order to experiment this breaking change on our projects before the official release. I'll check this on Monday.

2023-01-03 15:13 UTC, fargito commented
waiting for #417

2023-01-06 14:52 UTC, fargito requested changes
Careful about the commit titles, they should have an exclamation mark to set them as breaking

2023-01-27 16:38 UTC, adriencaccia requested changes

2023-01-27 16:38 UTC, adriencaccia commented on packages/serverless-contracts/src/types/http.ts
> +export enum StatusCodes {
As the library does not only export tools related to HTTP, we should name it `HttpStatusCodes` to be really explicit.

2023-02-03 09:54 UTC, adriencaccia commented
> Excellent work, thanks @Sc0ra and @StanHannebelle!
> 
> However I would prefer we create an alpha release in order to experiment this breaking change on our projects before the official release. I'll check this on Monday.

I took the liberty of changing the commit messages to explicit the breaking changes.

2023-02-13 08:29 UTC, adriencaccia requested changes

2023-02-13 08:29 UTC, adriencaccia commented on user-docs/documentation/docs/how-to-guides/3-migration-guides/4-output-schemas.md
> +Before version 0.25.0, in the `ApiGatewayContract`, the `outputSchema` key was used to specify the output schema of an Api Gateway integration.
Add a link to the release, even if it does not exist yet 🙈

2023-02-13 08:29 UTC, adriencaccia commented on user-docs/documentation/docs/how-to-guides/3-migration-guides/4-output-schemas.md
> +# From outputSchema to outputSchemas
```suggestion
# From `outputSchema` to `outputSchemas`
```

2023-02-13 08:29 UTC, adriencaccia commented on user-docs/documentation/docs/how-to-guides/3-migration-guides/4-output-schemas.md
> +1. Upgrade serverless-contracts to version 0.25.0 or higher
```suggestion
1. Upgrade `@swarmion/serverless-contracts` to version `0.25.0` or higher
```

2023-02-13 09:16 UTC, fargito commented on packages/serverless-contracts/src/contracts/apiGateway/features/openApiDocumentation.ts
> +          ] as OpenAPIV3.SchemaObject,
Add a comment here for improvement: given this PR, we will be able to be much more precise on the openAPI schema 🚀

2023-02-13 09:18 UTC, fargito commented on user-docs/documentation/docs/getting-started/5-add-a-new-serverless-contract-library.mdx
> +} from '@swarmion/serverless-contracts';
We need to update the generators as well

2023-02-16 17:04 UTC, fargito approved these changes

2023-02-17 08:46 UTC, adriencaccia approved these changes

2023-02-17 08:47 UTC, merged