Add Amplify deployment to NextJs example [reopened]
swarmion/swarmion pull request #433
Opened 2023-01-06 17:24 UTC by guiyom-e

Reopen PR #363

2023-01-09 11:23 UTC, adriencaccia requested changes
Great work @guiyom-e 🎉 

Let me know if everything is working as expected, and if it is we can merge 😃

2023-01-09 11:23 UTC, adriencaccia commented on examples/swarmion-with-next/frontend/next-app/README.md
> +Check out our [Next.js deployment documentation](https://nextjs.org/docs/deployment) for more details.
```suggestion
Check out the [Next.js deployment documentation](https://nextjs.org/docs/deployment) for more details.
```

2023-01-09 11:23 UTC, adriencaccia commented on examples/swarmion-with-next/frontend/next-app/hosting/bin.ts
> +  description: 'My Swarmion NextJS APP deployed with Amplify',
```suggestion
  description: 'Swarmion NextJS APP deployed with Amplify',
```

2023-01-09 11:23 UTC, adriencaccia commented on examples/swarmion-with-next/frontend/next-app/hosting/stack.ts
> +const AWS_AMPLIFY_RESOURCE_NAME = 'MyAmplifyAppWithSwarmion';
```suggestion
const AWS_AMPLIFY_RESOURCE_NAME = 'AmplifyAppWithSwarmion';
```

2023-01-09 11:23 UTC, adriencaccia commented on examples/swarmion-with-next/frontend/next-app/hosting/stack.ts
> +      description: 'My Swarmion NextJS APP deployed with Amplify',
```suggestion
      description: 'Swarmion NextJS APP deployed with Amplify',
```

2023-01-11 17:37 UTC, guiyom-e commented
> Great work @guiyom-e 🎉
> 
> Let me know if everything is working as expected, and if it is we can merge 😃

Hi @adriencaccia !
I have just tested to deploy swarmion-with-next project with Amplify, it is working properly!

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/46320048/211878115-f0b8cce4-1ce9-49e0-a710-f60bc9a68121.png">

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/46320048/211878133-78606011-aac8-4e4f-a798-c6020bf5b19c.png">

2023-01-12 08:42 UTC, adriencaccia approved these changes
Great work @guiyom-e 🎉

2023-01-12 08:51 UTC, merged