feat: remove shared API Gateways
swarmion/swarmion pull request #460
Opened 2023-01-13 17:11 UTC by fargito

2023-01-16 15:11 UTC, fargito commented
I think we can already merge this PR without the CDK part, as it already has value. Plus the PR is already quite big!

I will open another PR for the CDK part.

@adriencaccia is that ok for you?

2023-01-17 11:20 UTC, adriencaccia requested changes
Huge work @fargito 🎉

2023-01-17 11:20 UTC, adriencaccia commented on user-docs/documentation/docs/how-to-guides/2-use-swarmion-generators.md
> +By default, new packages will be placed in the `packages` directory. You can customize this with the `--directory` option. For example:
You switched the two paths, here we are talking about `services`

2023-01-17 11:20 UTC, adriencaccia commented on user-docs/documentation/docs/how-to-guides/2-use-swarmion-generators.md
> +pnpm nx generate @swarmion/nx-plugin:service myService --directory=path/to/packages
same here

2023-01-17 11:20 UTC, adriencaccia commented on user-docs/documentation/docs/how-to-guides/2-use-swarmion-generators.md
> +By default, new services will be placed in the `services` directory. You can customize this with the `--directory` option. For example:
Same here

2023-01-17 11:20 UTC, adriencaccia commented on user-docs/documentation/docs/how-to-guides/2-use-swarmion-generators.md
> +pnpm nx generate @swarmion/nx-plugin:service my-service --directory=path/to/services
Same here

2023-01-17 11:21 UTC, adriencaccia commented
> I think we can already merge this PR without the CDK part, as it already has value. Plus the PR is already quite big!
> 
> I will open another PR for the CDK part.
> 
> @adriencaccia is that ok for you?

Ok for me, let's work in this PR as is 👍

2023-01-17 13:27 UTC, fargito commented on examples/swarmion-starter/backend/core/serverless.ts
>    params: mergeStageParams(sharedParams, {
I fixed this! Also it seemed better to me to include the placeholder for future service-specific stage params

2023-01-17 14:42 UTC, adriencaccia approved these changes

2023-01-17 14:43 UTC, merged