Feat/remove http middlewares
swarmion/swarmion pull request #624
Opened 2023-04-14 16:18 UTC by Sc0ra

2023-04-14 16:24 UTC, GuillaumeLagrange approved these changes
lgtm to me, :crab: :crab: :crab:  middy is cone :crab: :crab: :crab:

2023-04-17 08:14 UTC, adriencaccia requested changes

2023-04-17 08:14 UTC, adriencaccia commented on packages/serverless-helpers/src/helpers/index.ts
> -export { applyHttpMiddlewares } from './applyHttpMiddlewares';
This commit is breaking, so you need to add a `!` character in the commit message, like so:
`feat(serverless-helpers)!: remove applyHttpMiddlewares helper`

2023-04-17 08:14 UTC, adriencaccia commented on user-docs/documentation/docs/how-to-guides/1-use-serverless-contracts/1-api-gateway.md
> +```ts
You should add the `title="path/to/file.ts` to make it easier to understand where this file is located/what it is

2023-04-17 08:14 UTC, adriencaccia commented on user-docs/documentation/docs/how-to-guides/1-use-serverless-contracts/1-api-gateway.md
>  ```ts
Idem, can you add it here also?

2023-04-24 10:10 UTC, merged